INSERT INTO users (name, age) VALUES("Matt", 12);
INSERT INTO users (name, age) VALUES("Ryan", 14);
INSERT INTO users (name, age) VALUES("Alicia", 23);
INSERT INTO users (name, age) VALUES("Fitz", 24);
INSERT INTO users (name, age) VALUES("Bob", 34);
INSERT INTO users (name, age) VALUES("Jack", 6);
INSERT INTO users (name, age) VALUES("Jill", 14);
INSERT INTO users (name, age) VALUES("Beth", 12);
INSERT INTO users (name, age) VALUES("Bill", 24);
INSERT INTO users (name, age) VALUES("Wade", 48);
INSERT INTO users (name, age) VALUES("Tom", 14);
INSERT INTO users (name, age) VALUES("Elise", 23);
INSERT INTO users (name, age) VALUES("Mike", 45);
INSERT INTO users (name, age) VALUES("Sarah", 34);
INSERT INTO users (name, age) VALUES("Matilda", 87);
INSERT INTO users (name, age) VALUES("Rose", 45);
INSERT INTO users (name, age) VALUES("Kim", 34);
INSERT INTO users (name, age) VALUES("Saul", 28);
INSERT INTO users (name, age) VALUES("Sally", 3);
INSERT INTO users (name, age) VALUES("Brian", 47);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Magic Arena", "Game", 30000, "January 5", "April 3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Two", "Game", 4050, "April 3", "April 5");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Three", "Movie", 500000, "August 7", "November 5");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Four", "Food", 450, "June 4", "June 5");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Five", "Trip", 50000, "July 4", "August 4");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Six", "Game", 450, "August 4", "April 1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Seven", "Game", 5000, "January 1", "February 4");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Eight", "Other", 560, "April 3", "July 6");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Nine", "Other", 50, "April 4", "June 4");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ten", "Game", 45, "August 2", "April 7");

INSERT INTO pledges (amount, user_id, project_id) VALUES(450, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES(45, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(50, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES(50, 12, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES(35, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES(450, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES(43, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES(45, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES(25, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES(69, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES(34, 5, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES(34, 15, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES(56, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(75, 12, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES(54, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES(75, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES(93, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES(90, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES(85, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES(75, 13, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES(43, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES(42, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES(65, 20, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES(92, 17, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES(21, 16, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES(20, 15, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES(51, 14, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES(50, 15, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES(43, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES(44, 4, 4);